/jet/home/gmooers/miniconda3/envs/CPU/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/ocean/projects/ees220005p/gmooers/Githubs/Neural_nework_parameterization/NN_training/run_training/Improved_run_Experiments/run_simple_big_data_new.py", line 46, in <module>
    ml_train_nn.train_wrapper(training_data_path=training_data_path,
  File "/ocean/projects/ees220005p/gmooers/Githubs/Neural_nework_parameterization/NN_training/run_training/Improved_run_Experiments/../../src/ml_train_nn_zarr.py", line 157, in train_wrapper
    model.load_state_dict(torch.load(savename))
  File "/jet/home/gmooers/miniconda3/envs/CPU/lib/python3.9/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/jet/home/gmooers/miniconda3/envs/CPU/lib/python3.9/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/jet/home/gmooers/miniconda3/envs/CPU/lib/python3.9/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/ocean/projects/ees220005p/gmooers/Investigations/Model_Performance/Saved_Models/small_data_test_epochs_4_lr_1e-07_inputs_148_outputs_245_.pkl'
